/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuggestRouteImport } from './routes/suggest'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as ShareRouteImport } from './routes/share'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LyricsRouteImport } from './routes/lyrics'
import { Route as EndlessRouteImport } from './routes/endless'
import { Route as DailyRouteImport } from './routes/daily'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VersusIndexRouteImport } from './routes/versus.index'
import { Route as AlbumsIndexRouteImport } from './routes/albums.index'
import { Route as VersusBotRouteImport } from './routes/versus.bot'
import { Route as VersusMatchIdRouteImport } from './routes/versus.$matchId'
import { Route as SettingsAlbumsRouteImport } from './routes/settings.albums'
import { Route as AlbumsAlbumIdRouteImport } from './routes/albums.$albumId'

const SuggestRoute = SuggestRouteImport.update({
  id: '/suggest',
  path: '/suggest',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareRoute = ShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LyricsRoute = LyricsRouteImport.update({
  id: '/lyrics',
  path: '/lyrics',
  getParentRoute: () => rootRouteImport,
} as any)
const EndlessRoute = EndlessRouteImport.update({
  id: '/endless',
  path: '/endless',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyRoute = DailyRouteImport.update({
  id: '/daily',
  path: '/daily',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VersusIndexRoute = VersusIndexRouteImport.update({
  id: '/versus/',
  path: '/versus/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumsIndexRoute = AlbumsIndexRouteImport.update({
  id: '/albums/',
  path: '/albums/',
  getParentRoute: () => rootRouteImport,
} as any)
const VersusBotRoute = VersusBotRouteImport.update({
  id: '/versus/bot',
  path: '/versus/bot',
  getParentRoute: () => rootRouteImport,
} as any)
const VersusMatchIdRoute = VersusMatchIdRouteImport.update({
  id: '/versus/$matchId',
  path: '/versus/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsAlbumsRoute = SettingsAlbumsRouteImport.update({
  id: '/albums',
  path: '/albums',
  getParentRoute: () => SettingsRoute,
} as any)
const AlbumsAlbumIdRoute = AlbumsAlbumIdRouteImport.update({
  id: '/albums/$albumId',
  path: '/albums/$albumId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/daily': typeof DailyRoute
  '/endless': typeof EndlessRoute
  '/lyrics': typeof LyricsRoute
  '/settings': typeof SettingsRouteWithChildren
  '/share': typeof ShareRoute
  '/stats': typeof StatsRoute
  '/suggest': typeof SuggestRoute
  '/albums/$albumId': typeof AlbumsAlbumIdRoute
  '/settings/albums': typeof SettingsAlbumsRoute
  '/versus/$matchId': typeof VersusMatchIdRoute
  '/versus/bot': typeof VersusBotRoute
  '/albums/': typeof AlbumsIndexRoute
  '/versus/': typeof VersusIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/daily': typeof DailyRoute
  '/endless': typeof EndlessRoute
  '/lyrics': typeof LyricsRoute
  '/settings': typeof SettingsRouteWithChildren
  '/share': typeof ShareRoute
  '/stats': typeof StatsRoute
  '/suggest': typeof SuggestRoute
  '/albums/$albumId': typeof AlbumsAlbumIdRoute
  '/settings/albums': typeof SettingsAlbumsRoute
  '/versus/$matchId': typeof VersusMatchIdRoute
  '/versus/bot': typeof VersusBotRoute
  '/albums': typeof AlbumsIndexRoute
  '/versus': typeof VersusIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/daily': typeof DailyRoute
  '/endless': typeof EndlessRoute
  '/lyrics': typeof LyricsRoute
  '/settings': typeof SettingsRouteWithChildren
  '/share': typeof ShareRoute
  '/stats': typeof StatsRoute
  '/suggest': typeof SuggestRoute
  '/albums/$albumId': typeof AlbumsAlbumIdRoute
  '/settings/albums': typeof SettingsAlbumsRoute
  '/versus/$matchId': typeof VersusMatchIdRoute
  '/versus/bot': typeof VersusBotRoute
  '/albums/': typeof AlbumsIndexRoute
  '/versus/': typeof VersusIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/daily'
    | '/endless'
    | '/lyrics'
    | '/settings'
    | '/share'
    | '/stats'
    | '/suggest'
    | '/albums/$albumId'
    | '/settings/albums'
    | '/versus/$matchId'
    | '/versus/bot'
    | '/albums/'
    | '/versus/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/daily'
    | '/endless'
    | '/lyrics'
    | '/settings'
    | '/share'
    | '/stats'
    | '/suggest'
    | '/albums/$albumId'
    | '/settings/albums'
    | '/versus/$matchId'
    | '/versus/bot'
    | '/albums'
    | '/versus'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/daily'
    | '/endless'
    | '/lyrics'
    | '/settings'
    | '/share'
    | '/stats'
    | '/suggest'
    | '/albums/$albumId'
    | '/settings/albums'
    | '/versus/$matchId'
    | '/versus/bot'
    | '/albums/'
    | '/versus/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  DailyRoute: typeof DailyRoute
  EndlessRoute: typeof EndlessRoute
  LyricsRoute: typeof LyricsRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  ShareRoute: typeof ShareRoute
  StatsRoute: typeof StatsRoute
  SuggestRoute: typeof SuggestRoute
  AlbumsAlbumIdRoute: typeof AlbumsAlbumIdRoute
  VersusMatchIdRoute: typeof VersusMatchIdRoute
  VersusBotRoute: typeof VersusBotRoute
  AlbumsIndexRoute: typeof AlbumsIndexRoute
  VersusIndexRoute: typeof VersusIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/suggest': {
      id: '/suggest'
      path: '/suggest'
      fullPath: '/suggest'
      preLoaderRoute: typeof SuggestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share': {
      id: '/share'
      path: '/share'
      fullPath: '/share'
      preLoaderRoute: typeof ShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lyrics': {
      id: '/lyrics'
      path: '/lyrics'
      fullPath: '/lyrics'
      preLoaderRoute: typeof LyricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/endless': {
      id: '/endless'
      path: '/endless'
      fullPath: '/endless'
      preLoaderRoute: typeof EndlessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily': {
      id: '/daily'
      path: '/daily'
      fullPath: '/daily'
      preLoaderRoute: typeof DailyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/versus/': {
      id: '/versus/'
      path: '/versus'
      fullPath: '/versus/'
      preLoaderRoute: typeof VersusIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/albums/': {
      id: '/albums/'
      path: '/albums'
      fullPath: '/albums/'
      preLoaderRoute: typeof AlbumsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/versus/bot': {
      id: '/versus/bot'
      path: '/versus/bot'
      fullPath: '/versus/bot'
      preLoaderRoute: typeof VersusBotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/versus/$matchId': {
      id: '/versus/$matchId'
      path: '/versus/$matchId'
      fullPath: '/versus/$matchId'
      preLoaderRoute: typeof VersusMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/albums': {
      id: '/settings/albums'
      path: '/albums'
      fullPath: '/settings/albums'
      preLoaderRoute: typeof SettingsAlbumsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/albums/$albumId': {
      id: '/albums/$albumId'
      path: '/albums/$albumId'
      fullPath: '/albums/$albumId'
      preLoaderRoute: typeof AlbumsAlbumIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SettingsRouteChildren {
  SettingsAlbumsRoute: typeof SettingsAlbumsRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAlbumsRoute: SettingsAlbumsRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  DailyRoute: DailyRoute,
  EndlessRoute: EndlessRoute,
  LyricsRoute: LyricsRoute,
  SettingsRoute: SettingsRouteWithChildren,
  ShareRoute: ShareRoute,
  StatsRoute: StatsRoute,
  SuggestRoute: SuggestRoute,
  AlbumsAlbumIdRoute: AlbumsAlbumIdRoute,
  VersusMatchIdRoute: VersusMatchIdRoute,
  VersusBotRoute: VersusBotRoute,
  AlbumsIndexRoute: AlbumsIndexRoute,
  VersusIndexRoute: VersusIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
